/**
 * 假数据
 */

var initJson = {
    "PROJECT_NAME" : "项目1",
    "DEPT_NAME" : "头部信息1",
    "BUILD_ADDR" : "头部信息2",
    "BUILD_DEPT" : "头部信息3",
    "IS_EDIT" : "1",
    "TASK_STATE" : "1",
    "BO_TEMPLATE_DETAIL_VER" : [{
                                 "BO_CONTENT_NAME": "模块一",
                                 "CONTENT_TYPE": "6",
                                 "BO_CHECK_PROJECT_ID": "",
                                 "BO_CONTENT_ID": "525B28B5DB0F03A6E0530100007F3D0F",
                                 "BO_SINGLE_PROJECT_ID": "51EB2EAF00A247BFE0530100007FFFF6",
                                 "BO_COOPERATE_ID": "",
                                 "BO_PROBLEM_ID": "",
                                 "BO_TEMPLATE_DETAIL_VER_ID": "sh-schedule-template-ver-4-1",
                                 "DOMAIN_ID": "10000",
                                 "BO_CURRENT_NUM": "0",
                                 "BO_TOTAL_NUM": "3",
                                 "BO_PROJECT_SECTION_ID": "",
                                 "PHOTO_ORDER": "1000",
                                 "BO_CRITICAL_POINT_VER" : [{
                                    "NEED_VALIDATE":"1",
                                    "NEED_COUNT":"1",
                                    "PHOTO_NAME_RULE":"",
                                    "POINT_RULE":"面板1信息",
                                    "BO_CRITICAL_POINT_VER_ID":"sh-schedule-point-ver-60",
                                    "PHOTO_NAME_REGEX":"*",
                                    "BO_TEMPLATE_VER_ID":"100",
                                    "BO_TEMPLATE_DETAIL_VER_ID":"sh-schedule-template-ver-4-1",
                                    "POINT_NAME":"面板1",
                                    "COUNTS":"1",
                                    "SMALL_PHOTO_PATH" : ['images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png'],
                                    "PHOTO_PATH" : ['images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png','images/test.png'],
                                    "PHOTO_TOTAL_NUM" : "1",
                                    "PHOTO_UPLOAD_NUM" : "0",
                                    "INSTANCE_PHOTO_PATH" : ['images/test.png','images/test.png'],
                                    "IS_INVOLVE" : "1",
                                    "UNINVOLVE_REASON" : ""
                                 },{
                                    "NEED_VALIDATE":"1",
                                    "NEED_COUNT":"1",
                                    "PHOTO_NAME_RULE":"",
                                    "POINT_RULE":"面板2信息",
                                    "BO_CRITICAL_POINT_VER_ID":"sh-schedule-point-ver-61",
                                    "PHOTO_NAME_REGEX":"*",
                                    "BO_TEMPLATE_VER_ID":"100",
                                    "BO_TEMPLATE_DETAIL_VER_ID":"sh-schedule-template-ver-4-1",
                                    "POINT_NAME":"面板2",
                                    "COUNTS":"1",
                                    "SMALL_PHOTO_PATH" : [],
                                    "PHOTO_PATH" : [],
                                    "PHOTO_TOTAL_NUM" : "0",
                                    "PHOTO_UPLOAD_NUM" : "0",
                                    "INSTANCE_PHOTO_PATH" : [],
                                    "IS_INVOLVE" : "1"
                                 },{
                                    "NEED_VALIDATE":"1",
                                    "NEED_COUNT":"1",
                                    "PHOTO_NAME_RULE":"",
                                    "POINT_RULE":"面板3信息",
                                    "BO_CRITICAL_POINT_VER_ID":"sh-schedule-point-ver-62",
                                    "PHOTO_NAME_REGEX":"*",
                                    "BO_TEMPLATE_VER_ID":"100",
                                    "BO_TEMPLATE_DETAIL_VER_ID":"sh-schedule-template-ver-4-1",
                                    "POINT_NAME":"面板3",
                                    "COUNTS":"1",
                                    "PHOTO_TOTAL_NUM" : "1",
                                    "PHOTO_UPLOAD_NUM" : "0",
                                    "SMALL_PHOTO_PATH" : [],
                                    "PHOTO_PATH" : [],
                                    "INSTANCE_PHOTO_PATH" : [],
                                    "IS_INVOLVE" : "0",
                                    "UNINVOLVE_REASON" : "理由：工程为微站，不涉及天面情况。"
                                 }]
                             },
                             {
                                 "BO_CONTENT_NAME": "模块二",
                                 "CONTENT_TYPE": "6",
                                 "BO_CHECK_PROJECT_ID": "",
                                 "BO_CONTENT_ID": "525B28B6176403A6E0530100007F3D0F",
                                 "BO_SINGLE_PROJECT_ID": "51EB2EAF00A247BFE0530100007FFFF6",
                                 "BO_COOPERATE_ID": "",
                                 "BO_PROBLEM_ID": "",
                                 "BO_TEMPLATE_DETAIL_VER_ID": "sh-schedule-template-ver-4-2",
                                 "DOMAIN_ID": "10000",
                                 "BO_CURRENT_NUM": "0",
                                 "BO_TOTAL_NUM": "1",
                                 "BO_PROJECT_SECTION_ID": "",
                                 "PHOTO_ORDER": "1000",
                                 "BO_CRITICAL_POINT_VER" : [{
                                    "NEED_VALIDATE":"1",
                                    "NEED_COUNT":"1",
                                    "PHOTO_NAME_RULE":"",
                                    "POINT_RULE":"面板1信息",
                                    "BO_CRITICAL_POINT_VER_ID":"sh-schedule-point-ver-67",
                                    "PHOTO_NAME_REGEX":"*",
                                    "BO_TEMPLATE_VER_ID":"100",
                                    "BO_TEMPLATE_DETAIL_VER_ID":"sh-schedule-template-ver-4-2",
                                    "POINT_NAME":"面板1",
                                    "COUNTS":"1",
                                    "SMALL_PHOTO_PATH" : [],
                                    "PHOTO_PATH" : [],
                                    "PHOTO_TOTAL_NUM" : "1",
                                    "PHOTO_UPLOAD_NUM" : "0",
                                    "INSTANCE_PHOTO_PATH" : [],
                                    "IS_INVOLVE" : "1",
                                    "UNINVOLVE_REASON" : ""
                                  }]
                             },
                             {
                                 "BO_CONTENT_NAME": "模块三",
                                 "CONTENT_TYPE": "6",
                                 "BO_CHECK_PROJECT_ID": "",
                                 "BO_CONTENT_ID": "525B28B61CDD03A6E0530100007F3D0F",
                                 "BO_SINGLE_PROJECT_ID": "51EB2EAF00A247BFE0530100007FFFF6",
                                 "BO_COOPERATE_ID": "",
                                 "BO_PROBLEM_ID": "",
                                 "BO_TEMPLATE_DETAIL_VER_ID": "sh-schedule-template-ver-4-3",
                                 "DOMAIN_ID": "1000",
                                 "BO_CURRENT_NUM": "0",
                                 "BO_TOTAL_NUM": "1",
                                 "BO_PROJECT_SECTION_ID": "",
                                 "PHOTO_ORDER": "1000",
                                 "BO_CRITICAL_POINT_VER" : [{
                                    "NEED_VALIDATE":"1",
                                    "NEED_COUNT":"1",
                                    "PHOTO_NAME_RULE":"",
                                    "POINT_RULE":"面板1信息",
                                    "BO_CRITICAL_POINT_VER_ID":"sh-schedule-point-ver-73",
                                    "PHOTO_NAME_REGEX":"*",
                                    "BO_TEMPLATE_VER_ID":"100",
                                    "BO_TEMPLATE_DETAIL_VER_ID":"sh-schedule-template-ver-4-3",
                                    "POINT_NAME":"面板1",
                                    "COUNTS":"1",
                                    "SMALL_PHOTO_PATH" : [],
                                    "PHOTO_PATH" : [],
                                    "PHOTO_TOTAL_NUM" : "1",
                                    "PHOTO_UPLOAD_NUM" : "0",
                                    "INSTANCE_PHOTO_PATH" : [],
                                    "IS_INVOLVE" : "1",
                                    "UNINVOLVE_REASON" : ""
                                  }]
                             },
                             {
                                 "BO_CONTENT_NAME": "模块四",
                                 "CONTENT_TYPE": "6",
                                 "BO_CHECK_PROJECT_ID": "",
                                 "BO_CONTENT_ID": "525B28B6246003A6E0530100007F3D0F",
                                 "BO_SINGLE_PROJECT_ID": "51EB2EAF00A247BFE0530100007FFFF6",
                                 "BO_COOPERATE_ID": "",
                                 "BO_PROBLEM_ID": "",
                                 "BO_TEMPLATE_DETAIL_VER_ID": "sh-schedule-template-ver-4-4",
                                 "DOMAIN_ID": "10000",
                                 "BO_CURRENT_NUM": "0",
                                 "BO_TOTAL_NUM": "1",
                                 "BO_PROJECT_SECTION_ID": "",
                                 "PHOTO_ORDER": "1000",
                                 "BO_CRITICAL_POINT_VER" : [{
                                    "NEED_VALIDATE":"1",
                                    "NEED_COUNT":"1",
                                    "PHOTO_NAME_RULE":"",
                                    "POINT_RULE":"面板1信息",
                                    "BO_CRITICAL_POINT_VER_ID":"sh-schedule-point-ver-80",
                                    "PHOTO_NAME_REGEX":"*",
                                    "BO_TEMPLATE_VER_ID":"100",
                                    "BO_TEMPLATE_DETAIL_VER_ID":"sh-schedule-template-ver-4-4",
                                    "POINT_NAME":"面板1",
                                    "COUNTS":"1",
                                    "SMALL_PHOTO_PATH" : [],
                                    "PHOTO_PATH" : [],
                                    "PHOTO_TOTAL_NUM" : "1",
                                    "PHOTO_UPLOAD_NUM" : "0",
                                    "INSTANCE_PHOTO_PATH" : [],
                                    "IS_INVOLVE" : "1",
                                    "UNINVOLVE_REASON" : ""
                                  }]
                             },
                             {
                                 "BO_CONTENT_NAME": "模块五",
                                 "CONTENT_TYPE": "6",
                                 "BO_CHECK_PROJECT_ID": "",
                                 "BO_CONTENT_ID": "525B28B6F40503A6E0530100007F3D0F",
                                 "BO_SINGLE_PROJECT_ID": "51EB2EAF00A247BFE0530100007FFFF6",
                                 "BO_COOPERATE_ID": "",
                                 "BO_PROBLEM_ID": "",
                                 "BO_TEMPLATE_DETAIL_VER_ID": "sh-schedule-template-ver-4-5",
                                 "DOMAIN_ID": "10000",
                                 "BO_CURRENT_NUM": "0",
                                 "BO_TOTAL_NUM": "0",
                                 "BO_PROJECT_SECTION_ID": "",
                                 "PHOTO_ORDER": "1000",
                                 "IS_COMPLETED":"1",
                                 "BO_CRITICAL_POINT_VER" : [{
                                    "NEED_VALIDATE":"2",
                                    "NEED_COUNT":"1",
                                    "PHOTO_NAME_RULE":"",
                                    "POINT_RULE":"面板1信息",
                                    "BO_CRITICAL_POINT_VER_ID":"sh-schedule-point-ver-83",
                                    "PHOTO_NAME_REGEX":"*",
                                    "BO_TEMPLATE_VER_ID":"100",
                                    "BO_TEMPLATE_DETAIL_VER_ID":"sh-schedule-template-ver-4-5",
                                    "POINT_NAME":"面板1",
                                    "COUNTS":"0",
                                    "SMALL_PHOTO_PATH" : [],
                                    "PHOTO_PATH" : [],
                                    "PHOTO_TOTAL_NUM" : "1",
                                    "PHOTO_UPLOAD_NUM" : "0",
                                    "INSTANCE_PHOTO_PATH" : [],
                                    "IS_INVOLVE" : "1",
                                    "UNINVOLVE_REASON" : ""
                                  }]
                             }]
}